[package]
description = "Yet Another Kalman Filter Implementation, with [no_std] supported"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "yakf"
repository = "https://github.com/wangxiaochuTHU/yakf"
version = "0.1.3"
exclude = [
    "target/*",
    ".gitignore",
    ".cargo/*",
    "Cargo.lock",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hifitime = "3.2.0"
itertools = "0.10.3"
log = "0.4"
nalgebra = "0.31.0"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.5"
libc-print = "0.1.19"
